### ISSUE TITLE
Problem for finetune VGG16 model

### ISSUE THREAD

**Issue by larsonwu0220** [joelthchao/tensorflow-finetune-flickr-style#1]
Hi, I try to modify your finetune.py and model.py in order to fine-tune VGG16 where converted from Caffe. I extracted VGG16_Tensorflow.npy via converting VGG16 Caffe model. The code shows error when I added "load_with_skip('VGG16_Tensorflow.npy', sess, ['fc8']) ", the error information is

```
Traceback (most recent call last):
  File "mff_vgg16.py", line 125, in <module>
    main()
  File "mff_vgg16.py", line 66, in main
    load_with_skip('VGG16_Tensorflow.npy', sess, ['fc8']) # Skip weights from fc8
  File "/home/larson/atensorflow_code/Document14C/finetune_example/network.py", line 19, in load_with_skip
    session.run(tf.get_variable(subkey).assign(data))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 497, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 455, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected float32, got 'weights' of type 'str' instead.
```

VGG16 model is 

```
@staticmethod
    def VGG16(_X, _dropout, n_class):
        # part 1 (conv-conv-pool)
        conv1_1 = conv(_X, 3, 3, 64, 1, 1, padding='SAME', name='conv1_1')
        conv1_2 = conv(conv1_1, 3, 3, 64, 1, 1, padding='SAME', name='conv1_2')
        pool1 = max_pool(conv1_2, 2, 2, 2, 2, padding='SAME', name='pool1')
        # part 2 (conv-conv-pool)
        conv2_1 = conv(pool1, 3, 3, 128, 1, 1, padding='SAME', name='conv2_1')
        conv2_2 = conv(conv2_1, 3, 3, 128, 1, 1, padding='SAME', name='conv2_2')
        pool2 = max_pool(conv2_2, 2, 2, 2, 2, padding='SAME', name='pool2')
        # part 3 (conv-conv-conv-pool)
        conv3_1 = conv(pool2, 3, 3, 256, 1, 1, padding='SAME', name='conv3_1')
        conv3_2 = conv(conv3_1, 3, 3, 256, 1, 1, padding='SAME', name='conv3_2')
        conv3_3 = conv(conv3_2, 3, 3, 256, 1, 1, padding='SAME', name='conv3_3')
        pool3 = max_pool(conv3_3, 2, 2, 2, 2, padding='SAME', name='pool3')
        # part 4 (conv-conv-conv-pool)
        conv4_1 = conv(pool3, 3, 3, 512, 1, 1, padding='SAME', name='conv4_1')
        conv4_2 = conv(conv4_1, 3, 3, 512, 1, 1, padding='SAME', name='conv4_2')
        conv4_3 = conv(conv4_2, 3, 3, 512, 1, 1, padding='SAME', name='conv4_3')
        pool4 = max_pool(conv4_3, 2, 2, 2, 2, padding='SAME', name='pool4')
        # part 5 (conv-conv-conv-pool)
        conv5_1 = conv(pool4, 3, 3, 512, 1, 1, padding='SAME', name='conv5_1')
        conv5_2 = conv(conv5_1, 3, 3, 512, 1, 1, padding='SAME', name='conv5_2')
        conv5_3 = conv(conv5_2, 3, 3, 512, 1, 1, padding='SAME', name='conv5_3')
        pool5 = max_pool(conv5_3, 2, 2, 2, 2, padding='SAME', name='pool5')
        # Layer 6 (fc-relu-drop)
        fc6 = tf.reshape(pool5, [-1, 7*7*512])
        fc6 = fc(fc6, 7*7*512, 4096, name='fc6')
        fc6 = dropout(fc6, _dropout)
        # Layer 7 (fc-relu-drop)
        fc7 = fc(fc6, 4096, 4096, name='fc7')
        fc7 = dropout(fc7, _dropout)
        # Layer 8 (fc-prob)
        fc8 = fc(fc7, 4096, n_class, relu=False, name='fc8')
        return fc8
```

How to modify the code ?
Thanks a lot !

**Comment by emqiongwu** [comment]
Did you figure out the problem? I got the same issue

**Comment by codeAshu** [comment]
It may be late, but for the people who reached here with the same problem you can use following code to solve this issue by using following function - 

```Python
def load_weights(self,weight_file, sess, skip_layers=[]):
        weights = np.load(weight_file)
        keys = sorted(weights.keys())
        for i, k in enumerate(keys):
            if k.strip() not in skip_layers:
                print i, k, np.shape(weights[k])
                sess.run(self.parameters[i].assign(weights[k]))
            else:
                print '>>>skipping ', i,k,np.shape(weights[k])
```
and you can call the function like this - 
```Python
model.load_weights(Constants.pretrained_model, sess,
                           skip_layers=['fc6_W', 'fc7_W', 'fc8_W', 'fc6_b', 'fc7_b', 'fc8_b'])
```
